#!/usr/bin/env zsh
REALNAME=$(cat ~/.author | head -n1)
DATE=$(date)
YEAR=$(date +%Y)
FILENAME=$(echo $1 | sed 's/[^/]*\///')
FILE=$(echo $FILENAME | sed 's/\..*//')
FILEBIG=$(echo $FILE | tr '[:lower:]' '[:upper:]')
FILEBIG_UNDERSCORE=$(echo $1 | sed -s 's/\./_/g' | tr '[:lower:]' '[:upper:]') 
sed	"s/%%AUTHOR%%/$REALNAME/g;
	s/%%DATE%%/$DATE/g;
	s/%%YEAR%%/$YEAR/g;
	s/%%FILENAME%%/$FILENAME/g;
	s/%%FILE%%/$FILE/g;
	s/%%FILEBIG%%/$FILEBIG/g;
  s/%%IFDEFS%%/$FILEBIG_UNDERSCORE/g;"
